###################################################################################
## Diane Klement
## May 10 2024
##
## Code to analyze the data generated by "14_rsf_spatial.R" script as a GLMM
##
###################################################################################

# Loading necessary packages
library(tidyverse)
library(lme4)

# Reset R's brain - removes all previous objects
rm(list=ls())

################################################################################
# Reading in data
d <- readRDS("data/rsf/rsf_data.rds")

##WEEK 10 pt 1
## creating a GLMM
##A. data import
# Change veg_reclass to a factor!!
d$veg_reclass <- as.factor(d$veg_reclass)
# Data inspection...
head(d)
# Variable names
names(d)
# Data import
d1 <- d[,c('ID', 'Used', 'veg_reclass', 'EucDist_feed5')]
unique(d1$veg_reclass)

# Load the necessary packages
library(lme4)

# run a null model
mNull <- glmer(Used ~ 1 + (1|ID), data = d, family = 'binomial')
# call model output
summary(mNull)
mNull

##running univariate models
#model with veg type
mVeg <- glmer(Used ~ veg_reclass + (1|ID), data = d, family = 'binomial')
#model with distance to feeder
mFeeder <- glmer(Used ~ EucDist_feed5 + (1|ID), data = d, family = 'binomial')
summary(mVeg)
summary(mFeeder)
# model with distance polynomial
mFeeder2 <- glmer(Used ~ EucDist_feed5 + I(EucDist_feed5^2) + (1|ID), data = d, family = 'binomial')
summary(mFeeder2)
summary(mNull)

#running the categorical model
mVEG <- glmer(Used ~ veg_reclass + (1|ID), data = d, family = 'binomial')
summary(mVEG)


##running a global model
library(lme4)
mGlobal <- glmer(Used ~ veg_reclass + EucDist_feed5 + (1|ID) , data = d, family = 'binomial')
mGlobal1 <- glmer(Used ~ veg_reclass + EucDist_feed5 + 
                    I(EucDist_feed5^2) + (1|ID), data = d, family = 'binomial')
summary(mGlobal1)
summary(d)

#including all dummy codes except for most common one - herb_grass
m1 <- glmer(Used ~  Non_veg + Closed_Tree_Canopy + 
              Open_Tree_Canopy + (1|ID), data = d, family = 'binomial')
summary(m1)


library(AICcmodavg)
aictab(list(mNull, mFeeder, mVeg, mFeeder2,
            mGlobal, mGlobal1),
       modnames = c('mNull', 'mFeeder', 'mVeg', 'mFeeder2',
                    'mGlobal', 'mGlobal1'),
       sort = T, nobs = 7)

##likelihood ratio test
mTop <- mNull
mNull_glm <- glm(Used~ 1, data = d, family = 'binomial')
# LRT using anova()
anova(mNull, mNull_glm, test = 'Chisq')

mTop <- mFeeder
library(lme4)

# Random effects and CI estimates
(fixed <- fixef(mTop))
(fixed.1 <- fixef(mTop1))

parms <- names(fixed) 
(fixedCI <- confint(mTop, level = 0.95, parm=parms, 
                    method='profile'))  # Change method to 'Wald' for speed
# Pull the coefficient estimates from the summary table
loTable <- as.data.frame(coef(summary(mTop)))[,1:2]
# Add the CIs
(loTable <- cbind(loTable, fixedCI))
(oTable <- exp(loTable))
#export table
write.csv(oTable, 'C:/Users/dklem/Documents/Classes/WILD 8321/TopModel_OddsRatio_PABURSF1.csv')

#coefficient plots
# Load ggplot2
library(ggplot2)

# Plot function
pTable <- loTable
pTable$params <- factor(rownames(loTable), levels = rownames(loTable))
names(pTable)[3:4] <- c('ll', 'ul')

# W/o intercept
windows()
qplot(params, Estimate, ymin=ll, ymax=ul, data=pTable[-1,],
      geom='pointrange') + 
  geom_hline(aes(yintercept = 0)) +
  coord_flip() +
  theme_bw()

# For random effects modes and CI estimates
(cV <- ranef(mTop, condVar=T))

d2 <- read.csv('C:/Users/dklem/Documents/Classes/WILD 8321/RSFdata_std_3rdOrder_Kernel_rand10x.csv')
knitr::kable(table(d2[d2$Used==1, 'ID'], d2[d2$Used==1, 'Year']), caption = "Table 3: Data counts by ID by Year")
# Load the lattice (plotting) library
library(lattice)

# Random effects modes and CI estimates
windows()
dotplot(cV)

1- exp(-0.539223)
1- exp(-0.277)
mFeeder
1- exp(-0.003731)
mFeeder

